#!/bin/bash
# ------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------
if ! command -v zsh &> /dev/null
then
  echo "Zsh is not installed. Please install zsh first."
  exit 1
fi

if ! command -v git &> /dev/null
then
  echo "Git is not installed. Please install git first."
  exit 1
fi

if [ "$SHELL" != "/bin/zsh" ]; then
  echo "Changing shell to zsh"
  chsh -s /bin/zsh
fi

# ------------------------------------------------------------
# Fetching shell configurations
# ------------------------------------------------------------
SHELL_DIR="$HOME/.shell"

if [ ! -d "$SHELL_DIR" ]; then
  echo "Cloning shell configuration..."
  git clone https://github.com/Spreadprism/zshell.git $SHELL_DIR

  if [ ! -d "$SHELL_DIR" ]; then
    echo "Failed to clone shell configuration"
    exit 1
  fi

  echo "Linking shell configurations..."
  # .zshrc
  rm -f $HOME/.zhsrc.bak
  mv $HOME/.zshrc $HOME/.zshrc.bak
  ln -s $SHELL_DIR/.zshrc $HOME/.zshrc
  # INFO: starship.toml
  rm -f $HOME/.config/starship.toml.bak
  mv $HOME/.config/starship.toml $HOME/.config/starship.toml.bak
  ln -s $SHELL_DIR/starship.toml $HOME/.config/starship.toml
fi
