#!/bin/bash
# ------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------
# TODO: Should add auto installation for these dependencies
if ! command -v zsh &> /dev/null
then
  echo "Zsh is not installed. Please install zsh first."
  exit 1
fi

if ! command -v git &> /dev/null
then
  echo "Git is not installed. Please install git first."
  exit 1
fi

if [ "$SHELL" != "/bin/zsh" ]; then
  echo "Changing shell to zsh"
  chsh -s /bin/zsh
fi

# ------------------------------------------------------------
# Fetching shell configurations
# ------------------------------------------------------------
SHELL_DIR="$HOME/.shell"

if [ ! -d "$SHELL_DIR" ]; then
  echo "Cloning shell configuration..."
  git clone https://github.com/Spreadprism/zshell.git $SHELL_DIR

  if [ ! -d "$SHELL_DIR" ]; then
    echo "Failed to clone shell configuration"
    exit 1
  fi
fi
# ------------------------------------------------------------
# Shell configs
# ------------------------------------------------------------
link_file() {
  source_file="$SHELL_DIR/$1"
  dest_file=$2

  bak_file="$dest_file.bak"

  rm -f $bak_file
  mv $dest_file $bak_file
  ln -s $source_file $dest_file
}

# ------------------------------------------------------------
echo "Linking shell configurations..."
# .zshrc
link_file .zshrc $HOME/.zshrc
link_file starship.toml $HOME/.config/starship.toml
